# -*- coding: utf-8 -*-
"""Codelab: variables python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y05ooLMqK7gJc13dl69tfTL_BN38PiWr
"""

temperatura = 1
temperatura_especifica = 1.22
informe = "Clima del mes de enero"
hace_frio = True

print(temperatura)
print(temperatura_especifica)
print(informe)
print(hace_frio)
resultado = 1+1

print(resultado)



# acerca del limite de los numeros enteros, no encontre que haya alguno, es decir, no tiene limite de tamanio.
# con respecto al limite de los numeros flotantes, encontre que su precision maxima esta limitada por 53 bits, aunque otras fuentes dicen que el limite es 64 bits